### PR TITLE
Cocoapods support - FINAL

### PR DESCRIPTION
**Pull request by alioguzhan**
Now we have `pod` support! 

[See it here](https://cocoapods.org/pods/FileWatcher).

I updated `README` file. See my changes. You can merge this.

-----------

Currently, I am the maintainer of `Cocoapods` repo. I can add you as owner so you can make updates and releases. But to do that you need to create a `pod` account from your terminal:

```bash
pod trunk register your-email-here 'Your name here' --description='My Macbook Pro'
```
More details [here](https://guides.cocoapods.org/making/getting-setup-with-trunk.html#getting-started).

Please tell me when you do that (with the registered e-mail) so I can add you as the owner of [Pod](https://cocoapods.org/pods/FileWatcher).

Thanks.

### CODE REVIEW

**Comment by eonist** [comment]
Ok I Added you AS a maintainer of the project. Its not enough to make cocoa pod working?

**Comment by alioguzhan** [comment]
> Ok I Added you AS a maintainer of the project. Its not enough to make cocoa pod working?

It is enough. I already published to the CocoaPods. See [this page](https://cocoapods.org/pods/FileWatcher). It is working!

But right now, I am the only maintainer of `CocoaPods Project` (not this repo). If you like to join as an owner to CocoaPods, I can add you as an owner.

**Comment by eonist** [comment]
Ah cool. Yeah do that. I need to start cocoapods to different frameworks asap 😅

**Comment by alioguzhan** [comment]
Ok then :D . just install cocoapods and run this command:

```bash
pod trunk register 30n1st@gmail.com 'Eonist'
```

Once you register and verify your e-mail, I will be able to add you as an owner to Cocoapods Repo 👍

**Comment by eonist** [comment]
✅

**Pull request merged**
