### PR TITLE
CocoaPods Support

### PR DESCRIPTION
**Pull request by alioguzhan**
Hey André, 

I tested this `.podspec` file on my local env. It looks fine. But, before merging this, we need to add a version tag to this repository. Specifically, `0.1.0`. Can you please create this tag and push it to the master?

```bash
$ git tag 0.1.0 && git push origin master --tags
```

Then we can merge this and **only then**, I will be able to test and publish it to official CocoaPods Repo. 

> PS: If you don't have time, You can assign me to maintainer role to make the required arrangements.

### CODE REVIEW

**Comment by alioguzhan** [comment]
Additionally, the library's name is currently `FileWatcher` which is too generic. Do you consider adding a prefix to it ? Like `FLFileWatcher` (FutureLab)

I can make the required updates.

**Comment by eonist** [comment]
We. An find another name maybe if all are taken on cocoapod? Prefixing Names is a bit archaic IMO.

**Comment by eonist** [comment]
Sure. Ill add you as maintainer tomorrow

**Comment by eonist** [comment]
Feel free to merge.

**Pull request merged**
